// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// psi_Q
arma::colvec psi_Q(arma::colvec u, double q, double k);
RcppExport SEXP MQRE_psi_Q(SEXP uSEXP, SEXP qSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::colvec >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    __result = Rcpp::wrap(psi_Q(u, q, k));
    return __result;
END_RCPP
}
// psi_Q_der
arma::colvec psi_Q_der(arma::colvec u, double q, double k);
RcppExport SEXP MQRE_psi_Q_der(SEXP uSEXP, SEXP qSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::colvec >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    __result = Rcpp::wrap(psi_Q_der(u, q, k));
    return __result;
END_RCPP
}
// singVal
arma::mat singVal(arma::mat m);
RcppExport SEXP MQRE_singVal(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type m(mSEXP);
    __result = Rcpp::wrap(singVal(m));
    return __result;
END_RCPP
}
// makeVMat
Rcpp::List makeVMat(arma::mat Z, double sigma_v, double sigma_e, int m);
RcppExport SEXP MQRE_makeVMat(SEXP ZSEXP, SEXP sigma_vSEXP, SEXP sigma_eSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_v(sigma_vSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_e(sigma_eSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    __result = Rcpp::wrap(makeVMat(Z, sigma_v, sigma_e, m));
    return __result;
END_RCPP
}
// RandEff
arma::colvec RandEff(arma::colvec y, arma::mat x, arma::mat Z, double sigma_v, double sigma_e, double m, arma::colvec beta, double tol, int maxit, double k, double k_v, double qtl, double k_val);
RcppExport SEXP MQRE_RandEff(SEXP ySEXP, SEXP xSEXP, SEXP ZSEXP, SEXP sigma_vSEXP, SEXP sigma_eSEXP, SEXP mSEXP, SEXP betaSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP kSEXP, SEXP k_vSEXP, SEXP qtlSEXP, SEXP k_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_v(sigma_vSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_e(sigma_eSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type k_v(k_vSEXP);
    Rcpp::traits::input_parameter< double >::type qtl(qtlSEXP);
    Rcpp::traits::input_parameter< double >::type k_val(k_valSEXP);
    __result = Rcpp::wrap(RandEff(y, x, Z, sigma_v, sigma_e, m, beta, tol, maxit, k, k_v, qtl, k_val));
    return __result;
END_RCPP
}
// EstFunc_ML2
Rcpp::List EstFunc_ML2(arma::colvec y, arma::mat x, arma::mat Z, double sigma_v, double sigma_e, double m, arma::colvec beta, double tol, int maxit, double k, double K2_val, double qtl, double k_val);
RcppExport SEXP MQRE_EstFunc_ML2(SEXP ySEXP, SEXP xSEXP, SEXP ZSEXP, SEXP sigma_vSEXP, SEXP sigma_eSEXP, SEXP mSEXP, SEXP betaSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP kSEXP, SEXP K2_valSEXP, SEXP qtlSEXP, SEXP k_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_v(sigma_vSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_e(sigma_eSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type K2_val(K2_valSEXP);
    Rcpp::traits::input_parameter< double >::type qtl(qtlSEXP);
    Rcpp::traits::input_parameter< double >::type k_val(k_valSEXP);
    __result = Rcpp::wrap(EstFunc_ML2(y, x, Z, sigma_v, sigma_e, m, beta, tol, maxit, k, K2_val, qtl, k_val));
    return __result;
END_RCPP
}
