# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

psi_Q <- function(u, q, k) {
    .Call('MQRE_psi_Q', PACKAGE = 'MQRE', u, q, k)
}

psi_Q_der <- function(u, q, k) {
    .Call('MQRE_psi_Q_der', PACKAGE = 'MQRE', u, q, k)
}

singVal <- function(m) {
    .Call('MQRE_singVal', PACKAGE = 'MQRE', m)
}

makeVMat <- function(Z, sigma_v, sigma_e, m) {
    .Call('MQRE_makeVMat', PACKAGE = 'MQRE', Z, sigma_v, sigma_e, m)
}

RandEff <- function(y, x, Z, sigma_v, sigma_e, m, beta, tol, maxit, k, k_v, qtl, k_val) {
    .Call('MQRE_RandEff', PACKAGE = 'MQRE', y, x, Z, sigma_v, sigma_e, m, beta, tol, maxit, k, k_v, qtl, k_val)
}

EstFunc_ML2 <- function(y, x, Z, sigma_v, sigma_e, m, beta, tol, maxit, k, K2_val, qtl, k_val) {
    .Call('MQRE_EstFunc_ML2', PACKAGE = 'MQRE', y, x, Z, sigma_v, sigma_e, m, beta, tol, maxit, k, K2_val, qtl, k_val)
}

